// ALL behaviour of the site lives here: the page, the upload API, history, undo, download.
// No platform import and no Node-only API. It receives:
//   store(name) -> { get(key,{type}), set(key,value), setJSON(key,value), delete(key) }
//   env         -> plain object of settings and secrets (see README-UPLOAD.md)
//   templates   -> { template, login, empty, uploadUi } strings (generated by scripts/build_templates.py)
// Tests pass an in-memory store; Netlify and Cloudflare each get a small adapter.

import { readXlsx } from './xlsx.js';
import { parseTape } from './parse-tape.js';
import { safeEqual, encryptPage, b64, unb64 } from './crypto.js';
import { renderDashboard, renderEmpty, loginPage, mdy } from './render.js';

// Mapbox PUBLIC token (pk.) for the map comes from the MAPBOX_TOKEN setting. It ships inside the page by design, so
// protect it with the URL restriction in the Mapbox account. Kept out of the repo so GitHub push protection accepts it.

const LOG_MAX = 1000;
const MAX_BYTES = 5 * 1024 * 1024;                 // Netlify Functions refuse request bodies over 6 MB
const FILE_KEY = /^\d{4}-\d{2}-\d{2}_\d{8}T\d{9}Z_[A-Za-z0-9._ -]{1,120}$/;
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const CHANGE_LIMIT = { positions: 0.25, basis: 0.35 };    // a bigger swing than this asks "are you sure?"

const SEC_HEADERS = {
  'x-robots-tag': 'noindex, nofollow',
  'x-frame-options': 'DENY',
  'x-content-type-options': 'nosniff',
  // strict-origin, not no-referrer: Mapbox checks the page address to enforce the token's URL restriction.
  'referrer-policy': 'strict-origin',
  'cache-control': 'no-store',
};

const json = (status, body) => new Response(JSON.stringify(body), { status, headers: { ...SEC_HEADERS, 'content-type': 'application/json; charset=utf-8' } });
const text = (status, body) => new Response(body, { status, headers: { ...SEC_HEADERS, 'content-type': 'text/plain; charset=utf-8' } });
const htmlRes = body => new Response(body, { status: 200, headers: { ...SEC_HEADERS, 'content-type': 'text/html; charset=utf-8' } });

const validDate = s => {
  if (!DATE_RE.test(s || '')) return false;
  const d = new Date(s + 'T00:00:00Z');
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s;
};

/** MM.DD.YYYY, MM_DD_YYYY, MM-DD-YYYY (or two-digit year) in a file name -> 'YYYY-MM-DD' | null */
export function asOfFromName(name) {
  // (\d{4}|\d{2}) order matters, or 2026 is read as 2020
  const m = /(\d{1,2})[._-](\d{1,2})[._-](\d{4}|\d{2})(?!\d)/.exec(String(name || ''));
  if (!m) return null;
  const iso = `${m[3].length === 2 ? '20' + m[3] : m[3]}-${m[1].padStart(2, '0')}-${m[2].padStart(2, '0')}`;
  return validDate(iso) ? iso : null;
}

const money = v => '$' + Math.round(v).toLocaleString('en-US');
const sumBasis = loans => loans.reduce((s, l) => s + (l.basis || 0), 0);

export function createHandler({ store, env = {}, templates, now = () => new Date() }) {
  const weeks = store('weeks'), meta = store('meta'), files = store('files');

  async function readIndex() {
    const ix = await meta.get('index', { type: 'json' });
    return { weeks: Array.isArray(ix?.weeks) ? [...ix.weeks].sort() : [] };
  }
  async function readLog() {
    const l = await meta.get('log', { type: 'json' });
    return Array.isArray(l) ? l : [];
  }
  async function record(entry) {                 // never lets a logging problem break the logged action
    try {
      const log = await readLog();
      log.push({ at: now().toISOString(), ...entry });
      await meta.setJSON('log', log.slice(-LOG_MAX));
    } catch (e) { console.error('upload log write failed', e); }
  }

  // ---------- the page ----------
  async function page(request) {
    if (request.method !== 'GET' && request.method !== 'HEAD') return text(405, 'Method not allowed');
    const open = env.OPEN_VIEW === '1';
    const pw = env.DASHBOARD_PASSWORD;
    const minLen = parseInt(env.MIN_PASSWORD_LENGTH || '16', 10) || 16;
    if (!open) {
      if (!pw) return text(500, 'The site is not configured: set the DASHBOARD_PASSWORD secret and redeploy.');
      if (pw.length < minLen) return text(500, `The viewer password is shorter than the required ${minLen} characters. Set a longer DASHBOARD_PASSWORD (or lower MIN_PASSWORD_LENGTH) and redeploy.`);
    }
    const ix = await readIndex();
    let html;
    if (!ix.weeks.length) html = renderEmpty({ templates });
    else {
      const [latest, before] = [ix.weeks[ix.weeks.length - 1], ix.weeks[ix.weeks.length - 2]];
      const current = await weeks.get(latest, { type: 'json' });
      if (!current) return text(500, `The stored week ${latest} is missing. Use Upload history to see what was uploaded.`);
      const prior = before ? await weeks.get(before, { type: 'json' }) : null;
      html = renderDashboard({ templates, current, prior, mapboxToken: env.MAPBOX_TOKEN || '' });
    }
    if (open) return htmlRes(html);
    // The salt is generated once and kept: a new salt on every upload would log everyone out.
    let saltB64 = await meta.get('salt');
    if (!saltB64) { saltB64 = b64(crypto.getRandomValues(new Uint8Array(16))); await meta.set('salt', saltB64); }
    const iter = parseInt(env.PBKDF2_ITERATIONS || '250000', 10) || 250000;
    const payload = await encryptPage(html, pw, unb64(saltB64), iter);
    return htmlRes(loginPage(templates, payload));
  }

  // ---------- the upload API ----------
  async function api(request) {
    if (request.method !== 'POST') return json(405, { ok: false, message: 'Use POST.' });
    if (!env.UPLOAD_PASSPHRASE) return json(500, { ok: false, message: 'Uploads are switched off: the UPLOAD_PASSPHRASE secret is not set on the host.' });
    let form;
    try { form = await request.formData(); } catch { return json(400, { ok: false, message: 'Could not read the upload form.' }); }
    // Checked before anything else is looked at, with a constant-time compare.
    if (!safeEqual(form.get('passphrase'), env.UPLOAD_PASSPHRASE)) return json(401, { ok: false, message: 'Wrong passphrase.' });

    switch (String(form.get('action') || 'upload')) {
      case 'upload': return upload(form);
      case 'undo': return undo();
      case 'log': return json(200, { ok: true, log: (await readLog()).slice().reverse() });
      case 'file': return download(String(form.get('key') || ''));
      default: return json(400, { ok: false, message: 'Unknown action.' });
    }
  }

  async function upload(form) {
    const file = form.get('file');
    if (!file || typeof file === 'string' || !file.size) return json(400, { ok: false, message: 'No file was attached.' });
    const name = String(file.name || 'packet.xlsx');
    // From here on every outcome is logged, rejections included. Only successful uploads keep their file.
    const reject = async (status, message, extra = {}) => {
      await record({ action: 'upload', file: name, bytes: file.size, result: 'rejected', status, message, ...extra });
      return json(status, { ok: false, message });
    };
    if (file.size > MAX_BYTES) return reject(413, `The file is ${(file.size / 1048576).toFixed(1)} MB; the limit is ${MAX_BYTES / 1048576} MB.`);

    // As-of date: a typed value wins, otherwise the file name.
    const typed = String(form.get('asOf') || '').trim();
    if (typed && !validDate(typed)) return reject(400, `The typed as-of date "${typed}" is not a real date (use YYYY-MM-DD).`);
    const asOf = typed || asOfFromName(name);
    if (!asOf) return reject(400, `Could not read an as-of date from the file name "${name}" (expected something like CREMX_Loan_Portfolio_10_09_2026.xlsx). Type the as-of date in the dialog instead.`);
    const tomorrow = new Date(now().getTime() + 864e5).toISOString().slice(0, 10);
    if (asOf > tomorrow) return reject(400, `The as-of date ${mdy(asOf)} is in the future. Check the file name or type the correct date.`, { asOf });

    // Read the workbook once, then validate it.
    const bytes = new Uint8Array(await file.arrayBuffer());
    let sheet;
    try { sheet = await readXlsx(bytes); } catch (e) { return reject(422, `Could not read the workbook: ${e.message} Nothing was changed.`, { asOf }); }
    const parsed = parseTape(sheet.rows, asOf);
    if (!parsed.ok) return reject(422, parsed.message, { asOf });
    const { loans, warnings } = parsed;

    // A wildly different book is usually the wrong file: ask before storing, store nothing on the 409.
    const ix = await readIndex();
    const ref = ix.weeks.filter(d => d < asOf).pop();
    if (ref) {
      const prev = await weeks.get(ref, { type: 'json' });
      if (prev?.loans?.length) {
        const reasons = [], keys = [];
        const dn = Math.abs(loans.length - prev.loans.length) / prev.loans.length;
        if (dn > CHANGE_LIMIT.positions) { keys.push(`n:${prev.loans.length}>${loans.length}`); reasons.push(`the number of positions goes from ${prev.loans.length} to ${loans.length}`); }
        const pb = sumBasis(prev.loans), nb = sumBasis(loans);
        if (pb > 0 && Math.abs(nb - pb) / pb > CHANGE_LIMIT.basis) { keys.push(`b:${Math.round(pb)}>${Math.round(nb)}`); reasons.push(`total Basis goes from ${money(pb)} to ${money(nb)}`); }
        if (keys.length) {
          const token = keys.sort().join('|');                  // recomputed here, so a stale or wrong token does not count
          if (form.get('confirmChange') !== token) {
            return json(409, { ok: false, needsConfirm: true, confirmToken: token,
              message: `Compared with the ${mdy(ref)} packet, ${reasons.join(' and ')}. That is a large change and may mean the wrong file. Continue and publish it anyway?` });
          }
        }
      }
    }

    // Save the original file first. If that fails nothing is published.
    const stamp = now().toISOString().replace(/[-:.]/g, '');
    const safeName = name.replace(/[^A-Za-z0-9._ -]/g, '_').slice(0, 120) || 'packet.xlsx';
    const fileKey = `${asOf}_${stamp}_${safeName}`;
    try { await files.set(fileKey, bytes); } catch (e) { console.error(e); return reject(500, 'Could not save the original file, so nothing was published. Try again.', { asOf }); }

    const replaced = ix.weeks.includes(asOf);
    const latestBefore = ix.weeks[ix.weeks.length - 1];
    const verb = replaced ? 'Replaced' : (!latestBefore || asOf > latestBefore) ? 'Published' : 'Filed in as history';
    try {
      await weeks.setJSON(asOf, { asOf, loans, sourceFile: name, uploadedAt: now().toISOString() });
      const next = [...new Set([...ix.weeks, asOf])].sort();
      await meta.setJSON('index', { weeks: next });             // written last: the commit point, so a half-finished upload is never visible
    } catch (e) { console.error(e); return reject(500, 'Could not store the week, so nothing was published. Try again.', { asOf }); }

    const compared = [...new Set([...ix.weeks, asOf])].sort().filter(d => d < asOf).pop();
    const message = `${verb} the ${mdy(asOf)} packet: ${loans.length} positions, ${money(sumBasis(loans))} Basis. `
      + (compared ? `Compared with ${mdy(compared)}.` : 'No earlier week to compare with yet.')
      + (verb === 'Filed in as history' ? ` The dashboard still shows ${mdy(latestBefore)}.` : '')
      + (warnings.length ? ' Note: ' + warnings.join('; ') + '.' : '');
    await record({ action: 'upload', file: name, bytes: file.size, asOf, result: 'ok', status: 200, message, verb, positions: loans.length, fileKey });
    return json(200, { ok: true, asOf, verb, message });
  }

  async function undo() {
    const ix = await readIndex();
    if (!ix.weeks.length) return json(409, { ok: false, message: 'There is nothing to undo.' });
    const last = ix.weeks[ix.weeks.length - 1];
    await meta.setJSON('index', { weeks: ix.weeks.slice(0, -1) });
    await weeks.delete(last);                                   // the saved original file and the log entries are kept
    const message = `Removed the ${mdy(last)} week. The dashboard now shows ${ix.weeks.length > 1 ? mdy(ix.weeks[ix.weeks.length - 2]) : 'no packet'}.`;
    await record({ action: 'undo', asOf: last, result: 'ok', status: 200, message, verb: 'Undo' });
    return json(200, { ok: true, message });
  }

  async function download(key) {
    // Only the exact key shape is accepted, so this can never read any other key (../meta/salt, meta:log, ...).
    if (!FILE_KEY.test(key)) return json(400, { ok: false, message: 'That is not a saved file.' });
    const data = await files.get(key, { type: 'arrayBuffer' });
    if (!data) return json(404, { ok: false, message: 'That file is no longer stored.' });
    const orig = key.replace(/^\d{4}-\d{2}-\d{2}_\d{8}T\d{9}Z_/, '');
    return new Response(data, { status: 200, headers: { ...SEC_HEADERS, 'content-type': XLSX_MIME, 'content-disposition': `attachment; filename="${orig}"` } });
  }

  return async function handle(request) {
    try {
      const { pathname } = new URL(request.url);
      if (pathname === '/api/upload') return await api(request);
      if (pathname === '/' || pathname === '/index.html') return await page(request);
      return text(404, 'Not found');
    } catch (e) {
      console.error(e);
      return text(500, 'Something went wrong on the server. If you were uploading, reload and check Upload history before trying again.');
    }
  };
}
