"""Packs src/*.html into functions-src/templates.js (one string per file).

The function bundle cannot read files at run time, so the page templates travel as
JavaScript strings. Run after editing anything in src/:   python scripts/build_templates.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILES = {'template': 'template.html', 'login': 'login.html', 'empty': 'empty.html', 'uploadUi': 'upload-ui.html'}


def js_string(text):
    # JSON is valid JS except for the two line-separator characters in older engines
    return json.dumps(text, ensure_ascii=False).replace('\u2028', '\u2028').replace('\u2029', '\u2029')


lines = ['// GENERATED by scripts/build_templates.py from src/*.html. Do not edit by hand.', 'export default {']
for key, name in FILES.items():
    lines.append(f'  {key}: {js_string((ROOT / "src" / name).read_text(encoding="utf-8"))},')
lines.append('};')
out = ROOT / 'functions-src' / 'templates.js'
out.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
print(f'wrote {out} ({out.stat().st_size:,} bytes)')
